### ISSUE TITLE
Unable to have dynamo-db-client as a maven dependency for version 1.2.0

### ISSUE THREAD

**Issue by 5331k** [awslabs/amazon-dynamodb-lock-client#43] opened 2019-10-16 14:50 UTC
I am using this dependency in my pom file, but unfortunately maven failed to read artifact however when i change version to 1.1.0 , everything works fine. :

com.amazonaws
dynamodb-lock-client
1.2.0

**Comment by 5331k** [comment] 2019-10-17 11:45
Any comments ?, Any help will be much appreciated

**Comment by CandleCandle** [comment] 2019-10-28 16:19
This appears to be a duplicate of #33

**Comment by shetsa-amzn** [comment] 2023-02-28 13:45
Newer version of Amazon DynamoDB Lock Client(1.2.0) available on Maven now

https://repo1.maven.org/maven2/com/amazonaws/dynamodb-lock-client/1.2.0/

This change includes AWS SDK upgraded to `2.20.8`

**Closed** 2023-02-28 13:45 UTC
